let allCols = [
    {group: '', field: 'id', label: 'ID', display: true},
{group: '', field: 'sku', label: 'SKU', display: true},
{group: '', field: 'au', label: 'Au', display: true},
{group: '', field: 'de', label: 'De', display: true},
{group: '', field: 'bikemateVisibility', label: 'Bikemate Visibility', display: true},
{group: '', field: 'mgiVisiblity', label: 'Mgi Visiblity', display: true},
{group: '', field: 'activeNeto', label: 'Active Neto', display: true},
{group: '', field: 'status', label: 'Status', display: true},
{group: '', field: 'productGroup1', label: 'Product Group 1', display: true},
{group: '', field: 'productGroup2', label: 'Product Group 2', display: true},
{group: '', field: 'fitment', label: 'Fitment', display: true},
{group: '', field: 'description', label: 'Description', display: true},
{group: '', field: 'unit', label: 'Unit', display: true},
{group: '', field: 'qty', label: 'Qty', display: true},
{group: '', field: 'brand', label: 'Brand', display: true},
{group: '', field: 'biketypes', label: 'Biketypes', display: true},
{group: '', field: 'models2012on', label: 'Models 2012 On', display: true},
{group: '', field: 'gS1EAN', label: 'GS1 EAN', display: true},
{group: '', field: 'ourNotes', label: 'Our Notes', display: true},
{group: '', field: 'weightkg', label: 'Weightkg', display: true},
{group: '', field: 'packType', label: 'Pack Type', display: true},
{group: '', field: 'packLength', label: 'Pack Length', display: true},
{group: '', field: 'packWidth', label: 'Pack Width', display: true},
{group: '', field: 'packHeight', label: 'Pack Height', display: true},
{group: '', field: 'packCubic', label: 'Pack Cubic', display: true},
{group: '', field: 'caliper', label: 'Caliper', display: true},
{group: '', field: 'alength', label: 'A length', display: true},
{group: '', field: 'awidth', label: 'A width', display: true},
{group: '', field: 'athickness', label: 'A thickness', display: true},
{group: '', field: 'blength', label: 'B length', display: true},
{group: '', field: 'bwidth', label: 'B width', display: true},
{group: '', field: 'bthickness', label: 'B thickness', display: true},
{group: '', field: 'customerNotes', label: 'Customer Notes', display: true},
{group: '', field: 'eListing', label: 'E Listing', display: true},
{group: '', field: 'eforMake', label: 'E for Make', display: true},
{group: '', field: 'euploadedNeto', label: 'E uploaded Neto', display: true},
{group: '', field: 'eDate', label: 'E Date', display: true},
{group: '', field: 'echeck', label: 'E check', display: true},
{group: '', field: 'euploadedeBay', label: 'E uploaded eBay', display: true},
{group: '', field: 'ebayactive', label: 'Ebay Active', display: true},
{group: '', field: 'ePhotobucket', label: 'E Photobucket', display: true},
{group: '', field: 'ePhotoMain', label: 'E Photo Main', display: true},
{group: '', field: 'ePhotoClear', label: 'E Photo Clear', display: true},
{group: '', field: 'ePhotoSide', label: 'E Photo Side', display: true},
{group: '', field: 'saleStatus', label: 'Sale Status', display: true},
{group: '', field: 'rRP', label: 'RRP', display: true},
{group: '', field: 'eBay', label: 'eBay', display: true},
{group: '', field: 'eBC', label: 'EBC', display: true},
{group: '', field: 'sBS', label: 'SBS', display: true},
{group: '', field: 'goldfren', label: 'Goldfren', display: true},
{group: '', field: 'braking', label: 'Braking', display: true},
{group: '', field: 'brembo', label: 'Brembo', display: true},
{group: '', field: 'ferodo', label: 'Ferodo', display: true},
{group: '', field: 'goodridge', label: 'Goodridge', display: true},
{group: '', field: 'premier', label: 'Premier', display: true},
{group: '', field: 'carbon', label: 'Carbon', display: true},
{group: '', field: 'galfer', label: 'Galfer', display: true},
{group: '', field: 'vesrah', label: 'Vesrah', display: true},
{group: '', field: 'lucas', label: 'Lucas', display: true},
{group: '', field: 'newFren', label: 'New Fren', display: true},
{group: '', field: 'dunlop', label: 'Dunlop', display: true},
{group: '', field: 'lockheed', label: 'Lockheed', display: true},
{group: '', field: 'bendix', label: 'Bendix', display: true},
];

export default allCols;