let allCols = [
    {group: '', field: 'id', label: 'ID', display: true, option: ''},
    {group: '', field: 'sku', label: 'SKU', display: true, option: 'normal'},
    {group: '', field: 'active', label: 'Active', display: true, option: 'yn'},
    {group: '', field: 'au', label: 'Au', display: true, option: 'yn'},
    {group: '', field: 'de', label: 'De', display: true, option: 'yn'},
    {group: '', field: 'metalGearvisibility', label: 'MetalGear Visibility', display: true, option: 'yn'},
    {group: '', field: 'bikematevisibility', label: 'Bikemate Visibility', display: true, option: 'yn'},
    {group: '', field: 'mgiVisibility', label: 'Mgi Visibility', display: true, option: 'yn'},
    {group: '', field: 'status', label: 'Status', display: true, option: 'normal'},
    {group: '', field: 'productGroup1', label: 'Product Group 1', display: true, option: 'normal'},
    {group: '', field: 'productGroup2', label: 'Product Group 2', display: true, option: 'normal'},
    {group: '', field: 'description', label: 'Description', display: true, option: 'normal'},
    {group: '', field: 'unit', label: 'Unit', display: true, option: 'normal'},
    {group: '', field: 'qty', label: 'Qty', display: true, option: 'normal'},
    {group: '', field: 'brand', label: 'Brand', display: true, option: 'normal'},
    {group: '', field: 'biketypes', label: 'Biketypes', display: true, option: 'normal'},
    {group: '', field: 'gS1EAN', label: 'GS1 EAN', display: true, option: 'normal'},
    {group: '', field: 'ourNotes', label: 'Our Notes', display: false, option: 'normal'},
    {group: '', field: 'customerNotes', label: 'Customer Notes', display: false, option: 'normal'},
    {group: '', field: 'weightkg', label: 'Weightkg', display: true, option: 'normal'},
    {group: '', field: 'packType', label: 'Pack Type', display: true, option: 'normal'},
    {group: '', field: 'packLength', label: 'Pack Length', display: true, option: 'normal'},
    {group: '', field: 'packHeight', label: 'Pack Height', display: true, option: 'normal'},
    {group: '', field: 'packWidth', label: 'Pack Width', display: true, option: 'normal'},
    {group: '', field: 'maxccDirt', label: 'Maxcc Dirt', display: true, option: ''},
    {group: '', field: 'packCubic', label: 'Pack Cubic', display: true, option: 'normal'},
    {group: '', field: 'maxccStreet', label: 'Max CC Street', display: true, option: ''},
    {group: '', field: 'chainSize', label: 'Chain Size', display: true, option: 'normal'},
    {group: '', field: 'chainType', label: 'Chain Type', display: true, option: 'normal'},
    {group: '', field: 'chainLinks', label: 'Chain Links', display: true, option: 'normal'},
    {group: '', field: 'chainTensileStrengthN', label: 'Chain Tensile Strength N', display: true, option: 'normal'},
    {group: '', field: 'chainColour', label: 'Chain Colour', display: true, option: 'normal'},
    {group: '', field: 'compRK', label: 'Comp RK', display: true, option: 'normal'},
    {group: '', field: 'eListing', label: 'E Listing', display: true, option: 'normal'},
    {group: '', field: 'eforMake', label: 'Efor Make', display: true, option: 'normal'},
    {group: '', field: 'euploadedNeto', label: 'Euploaded Neto', display: true, option: 'normal'},
    {group: '', field: 'eDate', label: 'E Date', display: true, option: 'normal'},
    {group: '', field: 'echeck', label: 'Echeck', display: true, option: 'normal'},
    {group: '', field: 'euploadedeBay', label: 'E uploaded eBay', display: true, option: 'normal'},
    {group: '', field: 'eBayactive', label: 'eBay active', display: true, option: 'normal'},
    {group: '', field: 'ePhotobucket', label: 'E Photobucket', display: true, option: 'normal'},
    {group: '', field: 'ePhotoMain', label: 'E Photo Main', display: true, option: 'normal'},
    {group: '', field: 'ePhotoClear', label: 'E Photo Clear', display: true, option: 'normal'},
    {group: '', field: 'ePhotoSide', label: 'E Photo Side', display: true, option: 'normal'},
    {group: '', field: 'salesStatus', label: 'Sales Status', display: true, option: 'normal'},
    {group: '', field: 'rRP', label: 'RRP', display: true, option: 'normal'},
    {group: '', field: 'eBay', label: 'eBay', display: true, option: 'normal'},
    {group: '', field: 'trade1', label: 'Trade 1', display: true, option: 'normal'},
    {group: '', field: 'trade2', label: 'Trade 2', display: true, option: 'normal'},
    {group: '', field: 'trade3', label: 'Trade 3', display: true, option: 'normal'},
    {group: '', field: 'distributorNZAUD', label: 'Distributor NZAUD', display: true, option: 'normal'},
    {group: '', field: 'distributorUSD', label: 'Distributor USD', display: true, option: 'normal'},
    {group: '', field: 'distributorEUR', label: 'Distributor EUR', display: true, option: 'normal'},
    {group: '', field: 'totalStock', label: 'Total Stock', display: true, option: 'normal'},
    {group: '', field: 'minStock', label: 'Min Stock', display: true, option: 'normal'},
    {group: '', field: 'maxStock', label: 'Max Stock', display: true, option: 'normal'},
    {group: '', field: 'supplier', label: 'Supplier', display: true, option: 'normal'},
    {group: '', field: 'supplierCode', label: 'Supplier Code', display: true, option: 'normal'},
    {group: '', field: 'supplierCurrency', label: 'Supplier Currency', display: true, option: 'normal'},
    {group: '', field: 'supplierCost', label: 'Supplier Cost', display: true, option: 'normal'},    
];

export default allCols;
